/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/


// input.js
var { Plugin, MarkdownView, ItemView, Notice } = require("obsidian");
var { PluginSettingTab, Setting } = require("obsidian");
var APPLE_STYLE_VIEW = "apple-style-converter";
var DEFAULT_SETTINGS = {
  theme: "github",
  themeColor: "blue",
  customColor: "#0366d6",
  fontFamily: "sans-serif",
  fontSize: 3,
  macCodeBlock: true,
  codeLineNumber: true,
  avatarUrl: "",
  avatarBase64: "",
  // Base64 编码的本地头像，优先级高于 avatarUrl
  enableWatermark: false,
  showImageCaption: true,
  // 关闭水印时是否显示图片说明文字
  // 多账号支持
  wechatAccounts: [],
  // [{ id, name, appId, appSecret }]
  defaultAccountId: "",
  // 代理设置
  proxyUrl: "",
  // Cloudflare Worker 等代理地址
  // 旧字段保留用于迁移检测
  wechatAppId: "",
  wechatAppSecret: ""
};
var MAX_ACCOUNTS = 5;
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
}
var WechatAPI = class {
  constructor(appId, appSecret, proxyUrl = "") {
    this.appId = appId;
    this.appSecret = appSecret;
    this.proxyUrl = proxyUrl;
    this.accessToken = "";
    this.expireTime = 0;
  }
  /**
   * 发送请求（如果配置了代理，通过代理发送）
   */
  async sendRequest(url, options = {}) {
    const { requestUrl } = require("obsidian");
    if (this.proxyUrl) {
      const proxyResponse = await requestUrl({
        url: this.proxyUrl,
        method: "POST",
        body: JSON.stringify({
          url,
          method: options.method || "GET",
          data: options.body ? JSON.parse(options.body) : void 0
        }),
        contentType: "application/json"
      });
      return proxyResponse.json;
    } else {
      const response = await requestUrl({ url, ...options });
      return response.json;
    }
  }
  async getAccessToken() {
    if (this.accessToken && Date.now() < this.expireTime - 3e5) {
      return this.accessToken;
    }
    const url = `https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${this.appId}&secret=${this.appSecret}`;
    const data = await this.sendRequest(url);
    if (data.access_token) {
      this.accessToken = data.access_token;
      this.expireTime = Date.now() + data.expires_in * 1e3;
      return this.accessToken;
    } else {
      throw new Error(`\u83B7\u53D6 Token \u5931\u8D25: ${data.errmsg || "\u672A\u77E5\u9519\u8BEF"} (${data.errcode || "??"})`);
    }
  }
  async uploadCover(blob) {
    const token = await this.getAccessToken();
    const url = `https://api.weixin.qq.com/cgi-bin/material/add_material?access_token=${token}&type=image`;
    return await this.uploadMultipart(url, blob, "media");
  }
  async uploadImage(blob) {
    const token = await this.getAccessToken();
    const url = `https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=${token}`;
    return await this.uploadMultipart(url, blob, "media");
  }
  async createDraft(article) {
    const token = await this.getAccessToken();
    const url = `https://api.weixin.qq.com/cgi-bin/draft/add?access_token=${token}`;
    const data = await this.sendRequest(url, {
      method: "POST",
      body: JSON.stringify({ articles: [article] })
    });
    if (data.media_id) {
      return data;
    }
    throw new Error(`\u521B\u5EFA\u8349\u7A3F\u5931\u8D25: ${data.errmsg || JSON.stringify(data)} (${data.errcode || "N/A"})`);
  }
  async getDraftList(offset = 0, count = 20) {
    const token = await this.getAccessToken();
    const url = `https://api.weixin.qq.com/cgi-bin/draft/batchget?access_token=${token}`;
    const data = await this.sendRequest(url, {
      method: "POST",
      body: JSON.stringify({ offset, count, no_content: 1 })
    });
    if (data.item) {
      return data.item;
    }
    return [];
  }
  async deleteDraft(mediaId) {
    const token = await this.getAccessToken();
    const url = `https://api.weixin.qq.com/cgi-bin/draft/delete?access_token=${token}`;
    const data = await this.sendRequest(url, {
      method: "POST",
      body: JSON.stringify({ media_id: mediaId })
    });
    if (data.errcode && data.errcode !== 0) {
      throw new Error(`\u5220\u9664\u8349\u7A3F\u5931\u8D25: ${data.errmsg}`);
    }
  }
  async uploadMultipart(url, blob, fieldName) {
    const { requestUrl } = require("obsidian");
    const mimeType = blob.type || "image/jpeg";
    const ext = mimeType.includes("gif") ? "gif" : mimeType.includes("png") ? "png" : "jpg";
    if (this.proxyUrl) {
      const arrayBuffer = await blob.arrayBuffer();
      const bytes = new Uint8Array(arrayBuffer);
      let binary = "";
      for (let i = 0; i < bytes.length; i++) {
        binary += String.fromCharCode(bytes[i]);
      }
      const base64Data = btoa(binary);
      const proxyResponse = await requestUrl({
        url: this.proxyUrl,
        method: "POST",
        body: JSON.stringify({
          url,
          method: "UPLOAD",
          // 特殊标记，告诉代理这是文件上传
          fileData: base64Data,
          fileName: `image.${ext}`,
          mimeType,
          fieldName
        }),
        contentType: "application/json"
      });
      const data = proxyResponse.json;
      if (data.media_id || data.url) {
        return data;
      } else {
        throw new Error(`\u5FAE\u4FE1API\u62A5\u9519: ${data.errmsg} (${data.errcode})`);
      }
    } else {
      const boundary = "----ObsidianWechatConverterBoundary" + Math.random().toString(36).substring(2);
      const arrayBuffer = await blob.arrayBuffer();
      const bytes = new Uint8Array(arrayBuffer);
      let header = `--${boundary}\r
`;
      header += `Content-Disposition: form-data; name="${fieldName}"; filename="image.${ext}"\r
`;
      header += `Content-Type: ${mimeType}\r
\r
`;
      const footer = `\r
--${boundary}--\r
`;
      const headerBytes = new TextEncoder().encode(header);
      const footerBytes = new TextEncoder().encode(footer);
      const bodyBytes = new Uint8Array(headerBytes.length + bytes.length + footerBytes.length);
      bodyBytes.set(headerBytes, 0);
      bodyBytes.set(bytes, headerBytes.length);
      bodyBytes.set(footerBytes, headerBytes.length + bytes.length);
      try {
        const response = await requestUrl({
          url,
          method: "POST",
          body: bodyBytes.buffer,
          headers: {
            "Content-Type": `multipart/form-data; boundary=${boundary}`
          }
        });
        const data = response.json;
        if (data.media_id || data.url) {
          return data;
        } else {
          throw new Error(`\u5FAE\u4FE1API\u62A5\u9519: ${data.errmsg} (${data.errcode})`);
        }
      } catch (error) {
        console.error("Upload Error:", error);
        throw new Error(`\u7F51\u7EDC\u8BF7\u6C42\u5931\u8D25: ${error.message}`);
      }
    }
  }
};
var AppleStyleView = class extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.currentHtml = null;
    this.converter = null;
    this.theme = null;
    this.lastActiveFile = null;
    this.sessionCoverBase64 = "";
    this.sessionDigest = "";
  }
  getViewType() {
    return APPLE_STYLE_VIEW;
  }
  getDisplayText() {
    return "\u{1F4DD} \u5FAE\u4FE1\u6392\u7248\u8F6C\u6362";
  }
  getIcon() {
    return "wand";
  }
  async onOpen() {
    console.log("\u{1F34E} \u8F6C\u6362\u5668\u9762\u677F\u6253\u5F00");
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("apple-converter-container");
    await this.loadDependencies();
    this.createSettingsPanel(container);
    this.previewContainer = container.createEl("div", {
      cls: "apple-converter-preview"
    });
    this.setPlaceholder();
    this.registerActiveFileChange();
    setTimeout(async () => {
      const activeView = this.app.workspace.getActiveViewOfType(MarkdownView);
      if (activeView && this.converter) {
        await this.convertCurrent(true);
      }
    }, 500);
  }
  /**
   * 监听活动文件切换
   */
  registerActiveFileChange() {
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", async () => {
        const activeView = this.app.workspace.getActiveViewOfType(MarkdownView);
        if (activeView && activeView.file) {
          this.lastActiveFile = activeView.file;
        }
        this.updateCurrentDoc();
        if (activeView && this.converter) {
          setTimeout(async () => {
            await this.convertCurrent(true);
          }, 300);
        }
      })
    );
    const debounce = (func, wait) => {
      let timeout;
      return function(...args) {
        const context = this;
        clearTimeout(timeout);
        timeout = setTimeout(() => func.apply(context, args), wait);
      };
    };
    const debouncedConvert = debounce(async () => {
      if (!this.containerEl.offsetParent) return;
      const activeView = this.app.workspace.getActiveViewOfType(MarkdownView);
      if (activeView && activeView.file && this.lastActiveFile && activeView.file.path === this.lastActiveFile.path) {
        await this.convertCurrent(true);
      }
    }, 500);
    this.registerEvent(
      this.app.workspace.on("editor-change", debouncedConvert)
    );
  }
  /**
   * 加载依赖库
   */
  async loadDependencies() {
    const adapter = this.app.vault.adapter;
    const basePath = this.plugin.manifest.dir;
    try {
      if (typeof markdownit === "undefined") {
        const mdContent = await adapter.read(`${basePath}/lib/markdown-it.min.js`);
        (0, eval)(mdContent);
      }
      if (typeof hljs === "undefined") {
        const hljsContent = await adapter.read(`${basePath}/lib/highlight.min.js`);
        (0, eval)(hljsContent);
      }
      const themeContent = await adapter.read(`${basePath}/themes/apple-theme.js`);
      (0, eval)(themeContent);
      const converterContent = await adapter.read(`${basePath}/converter.js`);
      (0, eval)(converterContent);
      if (!window.AppleTheme) throw new Error("AppleTheme failed to load");
      this.theme = new window.AppleTheme({
        theme: this.plugin.settings.theme,
        themeColor: this.plugin.settings.themeColor,
        customColor: this.plugin.settings.customColor,
        fontFamily: this.plugin.settings.fontFamily,
        fontSize: this.plugin.settings.fontSize,
        macCodeBlock: this.plugin.settings.macCodeBlock,
        codeLineNumber: this.plugin.settings.codeLineNumber
      });
      if (!window.AppleStyleConverter) throw new Error("AppleStyleConverter failed to load");
      let avatarSrc = "";
      if (this.plugin.settings.enableWatermark) {
        avatarSrc = this.plugin.settings.avatarBase64 || this.plugin.settings.avatarUrl || "";
      }
      const showCaption = this.plugin.settings.showImageCaption;
      this.converter = new window.AppleStyleConverter(this.theme, avatarSrc, showCaption, this.app);
      await this.converter.initMarkdownIt();
      console.log("\u2705 \u4F9D\u8D56\u52A0\u8F7D\u5B8C\u6210");
    } catch (error) {
      console.error("\u274C \u4F9D\u8D56\u52A0\u8F7D\u5931\u8D25:", error);
      new Notice("\u4F9D\u8D56\u52A0\u8F7D\u5931\u8D25: " + error.message);
    }
  }
  /**
   * 创建设置面板
   */
  createSettingsPanel(container) {
    const panel = container.createEl("div", { cls: "apple-settings-panel" });
    const header = panel.createEl("div", { cls: "apple-settings-header" });
    header.createEl("div", { cls: "apple-settings-title", text: "\u{1F4DD} \u5FAE\u4FE1\u516C\u4F17\u53F7\u8F6C\u6362\u5668" });
    this.currentDocLabel = header.createEl("div", { cls: "apple-current-doc", text: "\u672A\u9009\u62E9\u6587\u6863" });
    const details = panel.createEl("details", { cls: "apple-settings-details" });
    details.open = false;
    const summary = details.createEl("summary", { cls: "apple-settings-summary", text: "\u6837\u5F0F\u8BBE\u7F6E" });
    const settingsArea = details.createEl("div", { cls: "apple-settings-area" });
    this.createSection(settingsArea, "\u4E3B\u9898", (section) => {
      const grid = section.createEl("div", { cls: "apple-btn-grid" });
      const themes = AppleTheme.getThemeList();
      themes.forEach((t) => {
        const btn = grid.createEl("button", {
          cls: `apple-btn-theme ${this.plugin.settings.theme === t.value ? "active" : ""}`,
          text: t.label
        });
        btn.dataset.value = t.value;
        btn.addEventListener("click", () => this.onThemeChange(t.value, grid));
      });
    });
    this.createSection(settingsArea, "\u5B57\u4F53", (section) => {
      const select = section.createEl("select", { cls: "apple-select" });
      [
        { value: "sans-serif", label: "\u65E0\u886C\u7EBF" },
        { value: "serif", label: "\u886C\u7EBF" },
        { value: "monospace", label: "\u7B49\u5BBD" }
      ].forEach((opt) => {
        const option = select.createEl("option", { value: opt.value, text: opt.label });
        if (this.plugin.settings.fontFamily === opt.value) option.selected = true;
      });
      select.addEventListener("change", (e) => this.onFontFamilyChange(e.target.value));
    });
    this.createSection(settingsArea, "\u5B57\u53F7", (section) => {
      const grid = section.createEl("div", { cls: "apple-btn-row" });
      const sizes = [
        { value: 1, label: "\u5C0F" },
        { value: 2, label: "\u8F83\u5C0F" },
        { value: 3, label: "\u63A8\u8350" },
        { value: 4, label: "\u8F83\u5927" },
        { value: 5, label: "\u5927" }
      ];
      sizes.forEach((s) => {
        const btn = grid.createEl("button", {
          cls: `apple-btn-size ${this.plugin.settings.fontSize === s.value ? "active" : ""}`,
          text: s.label
        });
        btn.dataset.value = s.value;
        btn.addEventListener("click", () => this.onFontSizeChange(s.value, grid));
      });
    });
    this.createSection(settingsArea, "\u4E3B\u9898\u8272", (section) => {
      const grid = section.createEl("div", { cls: "apple-color-grid" });
      const colors = AppleTheme.getColorList();
      colors.forEach((c) => {
        const btn = grid.createEl("button", {
          cls: `apple-btn-color ${this.plugin.settings.themeColor === c.value ? "active" : ""}`
        });
        btn.dataset.value = c.value;
        btn.style.setProperty("--btn-color", c.color);
        btn.addEventListener("click", () => this.onColorChange(c.value, grid));
      });
      const customBtn = grid.createEl("button", {
        cls: `apple-btn-custom-text ${this.plugin.settings.themeColor === "custom" ? "active" : ""}`,
        text: "\u81EA\u5B9A\u4E49",
        title: "\u81EA\u5B9A\u4E49\u989C\u8272"
      });
      customBtn.dataset.value = "custom";
      const colorInput = grid.createEl("input", {
        type: "color",
        cls: "apple-color-picker-hidden"
      });
      colorInput.value = this.plugin.settings.customColor || "#000000";
      colorInput.style.visibility = "hidden";
      colorInput.style.width = "0";
      colorInput.style.height = "0";
      colorInput.style.position = "absolute";
      customBtn.addEventListener("click", () => {
        colorInput.click();
      });
      colorInput.addEventListener("input", (e) => {
        customBtn.style.setProperty("--btn-color", e.target.value);
      });
      colorInput.addEventListener("change", async (e) => {
        const newColor = e.target.value;
        customBtn.style.setProperty("--btn-color", newColor);
        this.plugin.settings.customColor = newColor;
        this.theme.update({ customColor: newColor });
        await this.onColorChange("custom", grid);
      });
    });
    this.createSection(settingsArea, "Mac \u98CE\u683C\u4EE3\u7801\u5757", (section) => {
      const toggle = section.createEl("label", { cls: "apple-toggle" });
      const checkbox = toggle.createEl("input", { type: "checkbox", cls: "apple-toggle-input" });
      checkbox.checked = this.plugin.settings.macCodeBlock;
      toggle.createEl("span", { cls: "apple-toggle-slider" });
      checkbox.addEventListener("change", () => this.onMacCodeBlockChange(checkbox.checked));
    });
    this.createSection(settingsArea, "\u663E\u793A\u4EE3\u7801\u884C\u53F7", (section) => {
      const toggle = section.createEl("label", { cls: "apple-toggle" });
      const checkbox = toggle.createEl("input", { type: "checkbox", cls: "apple-toggle-input" });
      checkbox.checked = this.plugin.settings.codeLineNumber;
      toggle.createEl("span", { cls: "apple-toggle-slider" });
      checkbox.addEventListener("change", () => this.onCodeLineNumberChange(checkbox.checked));
    });
    const actions = panel.createEl("div", { cls: "apple-actions" });
    const accounts = this.plugin.settings.wechatAccounts || [];
    if (accounts.length > 0) {
      const syncBtn = actions.createEl("button", {
        cls: "apple-btn-secondary",
        text: "\u4E00\u952E\u540C\u6B65\u5230\u8349\u7A3F\u7BB1"
      });
      syncBtn.addEventListener("click", () => this.showSyncModal());
    }
    const copyBtn = actions.createEl("button", {
      cls: "apple-btn-primary",
      text: "\u590D\u5236\u5230\u516C\u4F17\u53F7"
    });
    this.copyBtn = copyBtn;
    copyBtn.addEventListener("click", () => this.copyHTML());
    const openWechatBtn = actions.createEl("button", {
      cls: "apple-btn-secondary",
      text: "\u6253\u5F00\u516C\u4F17\u53F7\u540E\u53F0"
    });
    openWechatBtn.addEventListener("click", () => {
      const { exec } = require("child_process");
      exec('start "" "D:\\04_Software\\Doubao\\Doubao.exe" --saman-browser-entry "https://mp.weixin.qq.com"');
    });
  }
  /**
   * 创建账号选择器
   */
  createAccountSelector(parent) {
    const accounts = this.plugin.settings.wechatAccounts || [];
    if (accounts.length === 0) return;
    const section = parent.createEl("div", { cls: "apple-setting-section wechat-account-selector" });
    section.createEl("label", { cls: "apple-setting-label", text: "\u540C\u6B65\u8D26\u53F7" });
    const select = section.createEl("select", { cls: "wechat-account-select" });
    const defaultId = this.plugin.settings.defaultAccountId;
    for (const account of accounts) {
      const option = select.createEl("option", {
        value: account.id,
        text: account.id === defaultId ? `${account.name} (\u9ED8\u8BA4)` : account.name
      });
      if (account.id === defaultId) {
        option.selected = true;
      }
    }
    this.selectedAccountId = defaultId;
    select.addEventListener("change", (e) => {
      this.selectedAccountId = e.target.value;
    });
  }
  /**
   * 从文章内容中提取第一张图片作为封面
   */
  getFirstImageFromArticle() {
    if (!this.currentHtml) return null;
    const tempDiv = document.createElement("div");
    tempDiv.innerHTML = this.currentHtml;
    const imgs = Array.from(tempDiv.querySelectorAll("img"));
    for (const img of imgs) {
      if (img.alt === "logo") continue;
      if (img.src) return img.src;
    }
    return null;
  }
  /**
   * 从 frontmatter 提取元数据
   * 支持: title, description, cover, author
   */
  getFrontmatterMeta() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) return {};
    try {
      const cache = this.app.metadataCache.getFileCache(activeFile);
      const fm = cache == null ? void 0 : cache.frontmatter;
      if (!fm) return {};
      const meta = {};
      if (fm.title) meta.title = fm.title;
      if (fm.description) meta.description = fm.description;
      else if (fm.summary) meta.description = fm.summary;
      if (fm.author) meta.author = fm.author;
      if (fm.cover || fm.image) {
        const coverPath = fm.cover || fm.image;
        meta.coverPath = coverPath;
      }
      return meta;
    } catch (e) {
      return {};
    }
  }
  /**
   * 从 frontmatter cover 路径解析为可用的图片 src
   */
  async resolveFrontmatterCover() {
    const meta = this.getFrontmatterMeta();
    if (!meta.coverPath) return null;
    try {
      const activeFile = this.app.workspace.getActiveFile();
      if (!activeFile) return null;
      const linkPath = meta.coverPath;
      const tFile = this.app.metadataCache.getFirstLinkpathDest(
        linkPath.replace(/^!?\[\[/, "").replace(/\]\]$/, ""),
        activeFile.path
      );
      if (tFile) {
        return this.app.vault.getResourcePath(tFile);
      }
      if (/^(https?:\/\/|data:)/i.test(linkPath)) {
        return linkPath;
      }
    } catch (e) {
    }
    return null;
  }
  /**
   * 创建设置区块
   */
  createSection(parent, label, builder) {
    const section = parent.createEl("div", { cls: "apple-setting-section" });
    section.createEl("label", { cls: "apple-setting-label", text: label });
    const content = section.createEl("div", { cls: "apple-setting-content" });
    builder(content);
  }
  /**
   * 显示同步选项 Modal
   */
  async showSyncModal() {
    if (!this.currentHtml) {
      new Notice("\u274C \u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u7AE0\u8FDB\u884C\u8F6C\u6362");
      return;
    }
    const { Modal } = require("obsidian");
    const modal = new Modal(this.app);
    modal.titleEl.setText("\u540C\u6B65\u5230\u5FAE\u4FE1\u8349\u7A3F\u7BB1");
    modal.contentEl.addClass("wechat-sync-modal");
    const accounts = this.plugin.settings.wechatAccounts || [];
    const defaultId = this.plugin.settings.defaultAccountId;
    let selectedAccountId = defaultId;
    const fmMeta = this.getFrontmatterMeta();
    let coverBase64 = this.sessionCoverBase64;
    let fmCoverResolved = false;
    if (!coverBase64 && fmMeta.coverPath) {
      const resolved = await this.resolveFrontmatterCover();
      if (resolved) {
        coverBase64 = resolved;
        fmCoverResolved = true;
      }
    }
    if (!coverBase64) {
      coverBase64 = this.getFirstImageFromArticle();
    }
    const accountSection = modal.contentEl.createDiv({ cls: "wechat-modal-section" });
    accountSection.createEl("label", { text: "\u8D26\u53F7", cls: "wechat-modal-label" });
    const accountSelect = accountSection.createEl("select", { cls: "wechat-account-select" });
    for (const account of accounts) {
      const option = accountSelect.createEl("option", {
        value: account.id,
        text: account.id === defaultId ? `${account.name} (\u9ED8\u8BA4)` : account.name
      });
      if (account.id === defaultId) option.selected = true;
    }
    accountSelect.addEventListener("change", (e) => {
      selectedAccountId = e.target.value;
    });
    const coverSection = modal.contentEl.createDiv({ cls: "wechat-modal-section" });
    coverSection.createEl("label", { text: "\u5C01\u9762\u56FE", cls: "wechat-modal-label" });
    const coverContent = coverSection.createDiv({ cls: "wechat-modal-cover-content" });
    const coverPreview = coverContent.createDiv({ cls: "wechat-modal-cover-preview" });
    const updatePreview = () => {
      coverPreview.empty();
      if (coverBase64) {
        coverPreview.createEl("img", { attr: { src: coverBase64 } });
        syncBtn.disabled = false;
        syncBtn.setText("\u5F00\u59CB\u540C\u6B65");
        syncBtn.removeClass("apple-btn-disabled");
      } else {
        coverPreview.createEl("div", {
          text: "\u6682\u65E0\u5C01\u9762",
          cls: "wechat-modal-no-cover"
        });
        syncBtn.disabled = true;
        syncBtn.setText("\u8BF7\u5148\u8BBE\u7F6E\u5C01\u9762");
        syncBtn.addClass("apple-btn-disabled");
      }
    };
    const coverBtns = coverContent.createDiv({ cls: "wechat-modal-cover-btns" });
    const uploadBtn = coverBtns.createEl("button", { text: "\u4E0A\u4F20" });
    uploadBtn.onclick = () => {
      const input = document.createElement("input");
      input.type = "file";
      input.accept = "image/*";
      input.onchange = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = (event) => {
          coverBase64 = event.target.result;
          this.sessionCoverBase64 = coverBase64;
          updatePreview();
        };
        reader.readAsDataURL(file);
      };
      input.click();
    };
    const digestSection = modal.contentEl.createDiv({ cls: "wechat-modal-section" });
    digestSection.createEl("label", { text: "\u6587\u7AE0\u6458\u8981\uFF08\u53EF\u9009\uFF09", cls: "wechat-modal-label" });
    let autoDigest;
    if (fmMeta.description) {
      autoDigest = fmMeta.description.substring(0, 120);
    } else {
      const tempDiv = document.createElement("div");
      tempDiv.innerHTML = this.currentHtml || "";
      autoDigest = (tempDiv.textContent || "").replace(/\s+/g, " ").trim().substring(0, 45);
    }
    const digestInput = digestSection.createEl("textarea", {
      cls: "wechat-modal-digest-input",
      placeholder: "\u7559\u7A7A\u5219\u81EA\u52A8\u63D0\u53D6\u6587\u7AE0\u524D 45 \u5B57"
    });
    digestInput.value = autoDigest;
    digestInput.rows = 3;
    digestInput.style.width = "100%";
    digestInput.style.resize = "vertical";
    digestInput.maxLength = 120;
    const charCount = digestSection.createEl("div", {
      cls: "wechat-digest-count",
      text: `${digestInput.value.length}/120`,
      style: "text-align: right; font-size: 11px; color: var(--text-muted); margin-top: 4px; opacity: 0.7;"
    });
    digestInput.addEventListener("input", () => {
      charCount.setText(`${digestInput.value.length}/120`);
    });
    const btnRow = modal.contentEl.createDiv({ cls: "wechat-modal-buttons" });
    const cancelBtn = btnRow.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.onclick = () => modal.close();
    const syncBtn = btnRow.createEl("button", { text: "\u5F00\u59CB\u540C\u6B65", cls: "mod-cta" });
    updatePreview();
    syncBtn.onclick = async () => {
      if (!coverBase64) {
        new Notice("\u274C \u8BF7\u5148\u8BBE\u7F6E\u5C01\u9762\u56FE");
        return;
      }
      modal.close();
      this.selectedAccountId = selectedAccountId;
      this.sessionCoverBase64 = coverBase64;
      this.sessionDigest = digestInput.value.trim() || autoDigest || "\u4E00\u952E\u540C\u6B65\u81EA Obsidian";
      this.sessionFmMeta = fmMeta;
      await this.onSyncToWechat();
    };
    modal.open();
  }
  /**
   * 处理同步到微信逻辑
   */
  async onSyncToWechat() {
    const accounts = this.plugin.settings.wechatAccounts || [];
    const accountId = this.selectedAccountId || this.plugin.settings.defaultAccountId;
    const account = accounts.find((a) => a.id === accountId);
    if (!account) {
      new Notice("\u274C \u8BF7\u5148\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u6DFB\u52A0\u5FAE\u4FE1\u516C\u4F17\u53F7\u8D26\u53F7");
      return;
    }
    if (!this.currentHtml) {
      new Notice("\u274C \u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u7AE0\u8FDB\u884C\u8F6C\u6362");
      return;
    }
    const notice = new Notice(`\u{1F680} \u6B63\u5728\u4F7F\u7528 ${account.name} \u540C\u6B65...`, 0);
    try {
      const api = new WechatAPI(account.appId, account.appSecret, this.plugin.settings.proxyUrl);
      notice.setMessage("\u{1F5BC}\uFE0F \u6B63\u5728\u5904\u7406\u5C01\u9762\u56FE...");
      const coverSrc = this.sessionCoverBase64 || this.getFirstImageFromArticle();
      if (!coverSrc) {
        throw new Error("\u672A\u8BBE\u7F6E\u5C01\u9762\u56FE\uFF0C\u540C\u6B65\u5931\u8D25\u3002\u8BF7\u5728\u5F39\u7A97\u4E2D\u4E0A\u4F20\u5C01\u9762\u3002");
      }
      const coverBlob = await this.srcToBlob(coverSrc);
      const coverRes = await api.uploadCover(coverBlob);
      const thumb_media_id = coverRes.media_id;
      notice.setMessage("\u{1F4F8} \u6B63\u5728\u540C\u6B65\u6B63\u6587\u56FE\u7247...");
      const processedHtml = await this.processAllImages(this.currentHtml, api);
      const cleanedHtml = this.cleanHtmlForDraft(processedHtml);
      const activeFile = this.app.workspace.getActiveFile();
      const fmMeta = this.sessionFmMeta || this.getFrontmatterMeta();
      const fmTitle = fmMeta.title;
      const title = fmTitle || (activeFile ? activeFile.basename : "\u65E0\u6807\u9898\u6587\u7AE0");
      notice.setMessage("\u{1F50D} \u6B63\u5728\u68C0\u67E5\u91CD\u590D\u8349\u7A3F...");
      let shouldCreate = true;
      try {
        const drafts = await api.getDraftList(0, 20);
        const normalizedTitle = title.substring(0, 64).trim();
        const existing = drafts.find((d) => {
          var _a;
          const items = (_a = d.content) == null ? void 0 : _a.news_item;
          if (!items || items.length === 0) return false;
          return items[0].title.trim() === normalizedTitle;
        });
        if (existing) {
          notice.hide();
          const shouldOverwrite = confirm(
            `\u5DF2\u5B58\u5728\u540C\u540D\u8349\u7A3F\u300C${normalizedTitle}\u300D

\u70B9\u51FB"\u786E\u5B9A"\u8986\u76D6\u65E7\u8349\u7A3F\uFF0C\u70B9\u51FB"\u53D6\u6D88"\u521B\u5EFA\u65B0\u8349\u7A3F\u3002`
          );
          if (shouldOverwrite) {
            const overwriteNotice = new Notice("\u{1F5D1}\uFE0F \u6B63\u5728\u5220\u9664\u65E7\u8349\u7A3F...", 0);
            await api.deleteDraft(existing.media_id);
            overwriteNotice.hide();
          }
        }
      } catch (e) {
        console.warn("\u8349\u7A3F\u5217\u8868\u83B7\u53D6\u5931\u8D25\uFF0C\u8DF3\u8FC7\u91CD\u590D\u68C0\u6D4B:", e);
      }
      notice.setMessage("\u{1F4DD} \u6B63\u5728\u53D1\u9001\u5230\u5FAE\u4FE1\u8349\u7A3F\u7BB1...");
      const article = {
        title: title.substring(0, 64),
        content: cleanedHtml,
        thumb_media_id,
        author: fmMeta.author || account.author || "",
        digest: this.sessionDigest || "\u4E00\u952E\u540C\u6B65\u81EA Obsidian"
      };
      await api.createDraft(article);
      notice.hide();
      new Notice("\u2705 \u540C\u6B65\u6210\u529F\uFF01\u8BF7\u524D\u5F80\u5FAE\u4FE1\u516C\u4F17\u53F7\u540E\u53F0\u8349\u7A3F\u7BB1\u67E5\u770B");
    } catch (error) {
      notice.hide();
      console.error("Wechat Sync Error:", error);
      new Notice(`\u274C \u540C\u6B65\u5931\u8D25: ${error.message}`);
    }
  }
  /**
   * 将各种形式的 src (Base64, URL, 路径) 转为 Blob
   */
  async srcToBlob(src) {
    if (src.startsWith("data:")) {
      const resp = await fetch(src);
      return await resp.blob();
    }
    if (src.startsWith("app://") || src.startsWith("capacitor://")) {
      const resp = await fetch(src);
      return await resp.blob();
    }
    if (src.startsWith("http")) {
      const { requestUrl } = require("obsidian");
      const response = await requestUrl({ url: src });
      return new Blob([response.arrayBuffer], { type: "image/png" });
    }
    throw new Error("\u4E0D\u652F\u6301\u7684\u56FE\u7247\u6765\u6E90\uFF0C\u8BF7\u5C1D\u8BD5\u91CD\u65B0\u4E0A\u4F20\u5C01\u9762");
  }
  /**
   * 处理 HTML 中的所有图片，上传到微信并替换链接
   */
  async processAllImages(html, api) {
    const div = document.createElement("div");
    div.innerHTML = html;
    const imgs = Array.from(div.querySelectorAll("img"));
    const urlMap = /* @__PURE__ */ new Map();
    for (const img of imgs) {
      const originalSrc = img.src;
      if (urlMap.has(originalSrc)) {
        img.src = urlMap.get(originalSrc);
        continue;
      }
      try {
        const blob = await this.srcToBlob(originalSrc);
        const res = await api.uploadImage(blob);
        urlMap.set(originalSrc, res.url);
        img.src = res.url;
      } catch (err) {
        console.warn("\u56FE\u7247\u4E0A\u4F20\u5931\u8D25\uFF0C\u8DF3\u8FC7:", originalSrc, err);
      }
    }
    return div.innerHTML;
  }
  /**
   * 清理 HTML 以适配微信编辑器
   * 微信编辑器对嵌套列表支持不佳，需要：
   * 1. 处理嵌套列表父级 li 内的段落与行内内容（避免嵌套层级被打散）
   * 2. 将深层嵌套列表转为伪列表（避免微信扁平化）
   * 3. 移除嵌套 ul/ol 的 margin（避免被当成独立块）
   * 4. 移除空的 li 元素和空白文本节点
   */
  cleanHtmlForDraft(html) {
    const div = document.createElement("div");
    div.innerHTML = html;
    div.querySelectorAll("li").forEach((li) => {
      const hasNestedList = li.querySelector("ul, ol");
      if (!hasNestedList) return;
      Array.from(li.children).forEach((child) => {
        if (child.tagName === "P") {
          while (child.firstChild) {
            li.insertBefore(child.firstChild, child);
          }
          child.remove();
        }
      });
      const firstList = Array.from(li.children).find((child) => child.tagName === "UL" || child.tagName === "OL");
      if (!firstList) return;
      const nodesBeforeList = [];
      for (let node = li.firstChild; node && node !== firstList; node = node.nextSibling) {
        nodesBeforeList.push(node);
      }
      const meaningfulNodes = nodesBeforeList.filter(
        (node) => !(node.nodeType === Node.TEXT_NODE && !node.textContent.trim())
      );
      if (meaningfulNodes.length === 0) return;
      const blockTags = /* @__PURE__ */ new Set(["UL", "OL", "TABLE", "PRE", "BLOCKQUOTE", "SECTION", "FIGURE", "DIV"]);
      const hasBlock = meaningfulNodes.some(
        (node) => node.nodeType === Node.ELEMENT_NODE && blockTags.has(node.tagName)
      );
      if (hasBlock) return;
      const wrapper = document.createElement("span");
      const liStyle = li.getAttribute("style") || "";
      const lineHeightMatch = liStyle.match(/line-height:\s*[^;]+/i);
      const lineHeight = lineHeightMatch ? `${lineHeightMatch[0]};` : "";
      wrapper.setAttribute("style", `display:block;margin:0;padding:0;${lineHeight}`);
      meaningfulNodes.forEach((node) => wrapper.appendChild(node));
      li.insertBefore(wrapper, firstList);
    });
    const getListDepth = (list) => {
      let depth = 0;
      let current = list.parentElement;
      while (current) {
        if (current.tagName === "UL" || current.tagName === "OL") depth += 1;
        current = current.parentElement;
      }
      return depth;
    };
    const buildPseudoItems = (list, depth) => {
      const fragment = document.createDocumentFragment();
      const isOrdered = list.tagName === "OL";
      let index = 1;
      Array.from(list.children).forEach((li) => {
        if (li.tagName !== "LI") return;
        const nestedLists = Array.from(li.children).filter(
          (child) => child.tagName === "UL" || child.tagName === "OL"
        );
        const liStyle = li.getAttribute("style") || "";
        const indent = Math.max(0, depth - 1) * 20;
        const wrapper = document.createElement("p");
        wrapper.setAttribute(
          "style",
          `${liStyle} margin:0 0 4px ${indent}px; padding:0;`
        );
        const contentNodes = [];
        Array.from(li.childNodes).forEach((node) => {
          if (node.nodeType === Node.ELEMENT_NODE && (node.tagName === "UL" || node.tagName === "OL")) return;
          if (node.nodeType === Node.ELEMENT_NODE && node.tagName === "P") {
            const children = Array.from(node.childNodes);
            if (children.length && contentNodes.length) {
              contentNodes.push(document.createTextNode(" "));
            }
            children.forEach((child) => contentNodes.push(child));
            return;
          }
          contentNodes.push(node);
        });
        while (contentNodes.length > 0 && contentNodes[0].nodeType === Node.TEXT_NODE && !contentNodes[0].textContent.trim()) {
          contentNodes.shift();
        }
        if (contentNodes.length > 0 && contentNodes[0].nodeType === Node.TEXT_NODE) {
          contentNodes[0].textContent = contentNodes[0].textContent.replace(/^\s+/, "");
          if (!contentNodes[0].textContent) {
            contentNodes.shift();
          }
        }
        const hasContent = contentNodes.some((node) => {
          if (node.nodeType === Node.TEXT_NODE) return node.textContent.trim();
          return true;
        });
        if (hasContent) {
          contentNodes.forEach((node) => {
            if (node.nodeType !== Node.TEXT_NODE) return;
            node.textContent = node.textContent.replace(/\s*\n\s*/g, " ").replace(/\s{2,}/g, " ");
            if (!node.textContent.trim()) {
              node.remove();
            }
          });
          const markerText = isOrdered ? `${index}. ` : "\u2022 ";
          const firstText = contentNodes.find((node) => node.nodeType === Node.TEXT_NODE && node.textContent.trim());
          if (firstText) {
            firstText.textContent = markerText + firstText.textContent;
          } else {
            contentNodes.unshift(document.createTextNode(markerText));
          }
          contentNodes.forEach((node) => wrapper.appendChild(node));
          fragment.appendChild(wrapper);
        }
        nestedLists.forEach((nested) => {
          fragment.appendChild(buildPseudoItems(nested, depth + 1));
        });
        index += 1;
      });
      return fragment;
    };
    Array.from(div.querySelectorAll("ul, ol")).forEach((list) => {
      if (!div.contains(list)) return;
      const depth = getListDepth(list);
      if (depth < 2) return;
      const fragment = buildPseudoItems(list, depth);
      list.parentNode.insertBefore(fragment, list);
      list.remove();
    });
    div.querySelectorAll("li > ul, li > ol").forEach((nestedList) => {
      let style = nestedList.getAttribute("style") || "";
      style = style.replace(/margin:\s*[^;]+;?/gi, "");
      style = "margin: 0; " + style;
      nestedList.setAttribute("style", style);
    });
    div.querySelectorAll("li").forEach((li) => {
      if (!li.textContent.trim() && li.querySelectorAll("img, ul, ol").length === 0) {
        li.remove();
      }
    });
    div.querySelectorAll("ul, ol").forEach((list) => {
      Array.from(list.childNodes).forEach((node) => {
        if (node.nodeType === Node.TEXT_NODE && !node.textContent.trim()) {
          node.remove();
        }
      });
    });
    div.querySelectorAll("li").forEach((li) => {
      Array.from(li.childNodes).forEach((node) => {
        if (node.nodeType === Node.TEXT_NODE && !node.textContent.trim()) {
          node.remove();
        }
      });
    });
    return div.innerHTML;
  }
  // === 设置变更处理 ===
  async onThemeChange(value, grid) {
    this.plugin.settings.theme = value;
    await this.plugin.saveSettings();
    this.updateButtonActive(grid, value);
    this.theme.update({ theme: value });
    await this.convertCurrent(true);
  }
  async onFontFamilyChange(value) {
    this.plugin.settings.fontFamily = value;
    await this.plugin.saveSettings();
    this.theme.update({ fontFamily: value });
    await this.convertCurrent(true);
  }
  async onFontSizeChange(value, grid) {
    this.plugin.settings.fontSize = value;
    await this.plugin.saveSettings();
    this.updateButtonActive(grid, value);
    this.theme.update({ fontSize: value });
    await this.convertCurrent(true);
  }
  async onColorChange(value, grid) {
    this.plugin.settings.themeColor = value;
    await this.plugin.saveSettings();
    this.updateButtonActive(grid, value);
    this.theme.update({ themeColor: value });
    await this.convertCurrent(true);
  }
  async onMacCodeBlockChange(checked) {
    this.plugin.settings.macCodeBlock = checked;
    await this.plugin.saveSettings();
    this.theme.update({ macCodeBlock: checked });
    if (this.converter) {
      this.converter.reinit();
      await this.converter.initMarkdownIt();
    }
    await this.convertCurrent(true);
  }
  async onCodeLineNumberChange(checked) {
    this.plugin.settings.codeLineNumber = checked;
    await this.plugin.saveSettings();
    this.theme.update({ codeLineNumber: checked });
    if (this.converter) {
      this.converter.reinit();
      await this.converter.initMarkdownIt();
    }
    await this.convertCurrent(true);
  }
  updateButtonActive(grid, value) {
    grid.querySelectorAll("button").forEach((btn) => {
      btn.classList.toggle("active", btn.dataset.value == value);
    });
  }
  /**
   * 更新当前文档显示
   */
  updateCurrentDoc() {
    const activeView = this.app.workspace.getActiveViewOfType(MarkdownView);
    if (activeView && this.currentDocLabel) {
      this.currentDocLabel.setText(`\u{1F4C4} ${activeView.file.basename}`);
      this.currentDocLabel.style.color = "#0071e3";
    } else if (this.lastActiveFile && this.currentDocLabel) {
      this.currentDocLabel.setText(`\u{1F4C4} ${this.lastActiveFile.basename}`);
      this.currentDocLabel.style.color = "#0071e3";
    } else if (this.currentDocLabel) {
      this.currentDocLabel.setText("\u672A\u9009\u62E9\u6587\u6863");
      this.currentDocLabel.style.color = "#86868b";
    }
  }
  /**
   * 设置占位符
   */
  setPlaceholder() {
    this.previewContainer.empty();
    this.previewContainer.removeClass("apple-has-content");
    const placeholder = this.previewContainer.createEl("div", { cls: "apple-placeholder" });
    placeholder.createEl("div", { cls: "apple-placeholder-icon", text: "\u{1F4DD}" });
    placeholder.createEl("h2", { text: "\u5FAE\u4FE1\u516C\u4F17\u53F7\u6392\u7248\u8F6C\u6362\u5668" });
    placeholder.createEl("p", { text: "\u5C06 Markdown \u8F6C\u6362\u4E3A\u7CBE\u7F8E\u7684 HTML\uFF0C\u4E00\u952E\u590D\u5236\u5230\u516C\u4F17\u53F7" });
    const steps = placeholder.createEl("div", { cls: "apple-steps" });
    steps.createEl("div", { text: "1\uFE0F\u20E3 \u6253\u5F00\u9700\u8981\u8F6C\u6362\u7684 Markdown \u6587\u4EF6" });
    steps.createEl("div", { text: "2\uFE0F\u20E3 \u9884\u89C8\u533A\u4F1A\u81EA\u52A8\u663E\u793A\u8F6C\u6362\u6548\u679C" });
    steps.createEl("div", { text: "3\uFE0F\u20E3 \u70B9\u51FB\u300C\u590D\u5236\u5230\u516C\u4F17\u53F7\u300D\u7C98\u8D34\u5373\u53EF" });
    const note = placeholder.createEl("p", {
      text: "\u6CE8\u610F\uFF1A\u5982\u5F53\u524D\u5DF2\u6253\u5F00\u6587\u6863\u4F46\u672A\u663E\u793A\uFF0C\u8BF7\u91CD\u65B0\u70B9\u51FB\u4E00\u4E0B\u6587\u6863\u5373\u53EF\u89E6\u53D1",
      cls: "apple-placeholder-note"
    });
  }
  /**
   * 转换当前文档
   */
  async convertCurrent(silent = false) {
    let activeView = this.app.workspace.getActiveViewOfType(MarkdownView);
    let markdown = "";
    let sourcePath = "";
    if (!activeView && this.lastActiveFile) {
      try {
        markdown = await this.app.vault.read(this.lastActiveFile);
        sourcePath = this.lastActiveFile.path;
      } catch (error) {
        if (!silent) new Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
        return;
      }
    } else if (activeView) {
      markdown = activeView.editor.getValue();
      if (activeView.file) sourcePath = activeView.file.path;
    } else {
      if (!silent) new Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
      return;
    }
    if (!markdown.trim()) {
      if (!silent) new Notice("\u5F53\u524D\u6587\u4EF6\u5185\u5BB9\u4E3A\u7A7A");
      return;
    }
    try {
      if (!silent) new Notice("\u26A1 \u6B63\u5728\u8F6C\u6362...");
      if (this.converter) this.converter.updateSourcePath(sourcePath);
      const html = await this.converter.convert(markdown);
      this.currentHtml = html;
      this.sessionCoverBase64 = null;
      const scrollTop = this.previewContainer.scrollTop;
      this.previewContainer.innerHTML = html;
      this.previewContainer.scrollTop = scrollTop;
      this.previewContainer.addClass("apple-has-content");
      this.updateCurrentDoc();
      if (!silent) new Notice("\u2705 \u8F6C\u6362\u6210\u529F\uFF01");
    } catch (error) {
      console.error("\u8F6C\u6362\u5931\u8D25:", error);
      if (!silent) new Notice("\u274C \u8F6C\u6362\u5931\u8D25: " + error.message);
    }
  }
  /**
   * 视图改变大小时触发 (包括侧边栏展开、Tab切换等导致的大小变化)
   */
  onResize() {
    super.onResize();
    if (this.resizeTimeout) clearTimeout(this.resizeTimeout);
    if (!this.containerEl.offsetParent) return;
    this.resizeTimeout = setTimeout(() => {
      this.convertCurrent(true);
    }, 300);
  }
  /**
   * 渲染 HTML
   */
  renderHTML(html) {
    this.previewContainer.empty();
    this.previewContainer.innerHTML = html;
  }
  /**
   * 复制 HTML
   */
  async copyHTML() {
    if (this.isCopying) return;
    if (!this.currentHtml) {
      if (this.copyBtn) {
        const originalText2 = this.copyBtn.innerHTML;
        this.copyBtn.setText("\u26A0\uFE0F \u8BF7\u5148\u8F6C\u6362\u6587\u6863");
        setTimeout(() => {
          if (this.copyBtn) this.copyBtn.innerHTML = originalText2;
        }, 2e3);
      }
      return;
    }
    const originalText = this.copyBtn.innerHTML;
    this.isCopying = true;
    if (this.copyBtn) {
      this.copyBtn.disabled = true;
      this.copyBtn.setText("\u6B63\u5728\u5904\u7406...");
    }
    try {
      const tempDiv = document.createElement("div");
      tempDiv.innerHTML = this.currentHtml;
      const processed = await this.processImagesToDataURL(tempDiv);
      if (this.copyBtn) {
        this.copyBtn.setText("\u6B63\u5728\u590D\u5236...");
      }
      const cleanedHtml = this.cleanHtmlForDraft(tempDiv.innerHTML);
      const text = tempDiv.textContent || "";
      const htmlContent = cleanedHtml;
      if (navigator.clipboard && navigator.clipboard.write) {
        const clipboardItem = new ClipboardItem({
          "text/html": new Blob([htmlContent], { type: "text/html" }),
          "text/plain": new Blob([text], { type: "text/plain" })
        });
        await navigator.clipboard.write([clipboardItem]);
        if (this.copyBtn) {
          this.copyBtn.setText("\u2705 \u5DF2\u590D\u5236\uFF01");
          setTimeout(() => {
            if (this.copyBtn) {
              this.copyBtn.disabled = false;
              this.copyBtn.innerHTML = originalText;
            }
          }, 2e3);
        }
        return;
      }
      throw new Error("Clipboard API unavailable");
    } catch (error) {
      console.error("\u590D\u5236\u5931\u8D25:", error);
      if (this.copyBtn) {
        this.copyBtn.setText("\u274C \u590D\u5236\u5931\u8D25");
        setTimeout(() => {
          this.copyBtn.disabled = false;
          this.copyBtn.innerHTML = originalText;
        }, 2e3);
      }
    } finally {
      this.isCopying = false;
    }
  }
  /**
   * 将 HTML 中的本地图片转换为 Base64 (Canvas Compressed)
   */
  async processImagesToDataURL(container) {
    const images = Array.from(container.querySelectorAll("img"));
    const localImages = images.filter((img) => img.src.startsWith("app://"));
    if (localImages.length === 0) return false;
    const total = localImages.length;
    const concurrency = 3;
    let processed = 0;
    for (let i = 0; i < localImages.length; i += concurrency) {
      const chunk = localImages.slice(i, i + concurrency);
      await Promise.all(chunk.map((img) => this.convertImageToLocally(img)));
      processed += chunk.length;
      if (this.copyBtn) {
        this.copyBtn.setText(`\u6B63\u5728\u5904\u7406\u56FE\u7247 ${processed}/${total}...`);
      }
    }
    const elapsed = Date.now() - startTime;
    const minDuration = 800;
    if (elapsed < minDuration) {
      await new Promise((resolve) => setTimeout(resolve, minDuration - elapsed));
    }
    return true;
  }
  async convertImageToLocally(img) {
    try {
      const response = await fetch(img.src);
      const blob = await response.blob();
      if (blob.size > 10 * 1024 * 1024) {
        new Notice(`\u26A0\uFE0F \u53D1\u73B0\u5927\u56FE (${(blob.size / 1024 / 1024).toFixed(1)}MB)\uFF0C\u5904\u7406\u53EF\u80FD\u8F83\u6162`, 5e3);
      }
      let dataUrl;
      if (blob.type === "image/gif") {
        dataUrl = await this.blobToDataUrl(blob);
      } else {
        dataUrl = await this.blobToJpegDataUrl(blob);
      }
      img.src = dataUrl;
      delete img.dataset.src;
    } catch (error) {
      console.error("Image processing failed:", error);
    }
  }
  // Helper: Direct Blob to Base64 (for GIFs)
  blobToDataUrl(blob) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  }
  blobToJpegDataUrl(blob) {
    return new Promise((resolve, reject) => {
      const url = URL.createObjectURL(blob);
      const image = new Image();
      image.onload = () => {
        const canvas = document.createElement("canvas");
        let width = image.width;
        let height = image.height;
        if (width > 1920) {
          height = Math.round(height * (1920 / width));
          width = 1920;
        }
        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext("2d");
        ctx.drawImage(image, 0, 0, width, height);
        const dataUrl = canvas.toDataURL("image/jpeg", 0.8);
        URL.revokeObjectURL(url);
        resolve(dataUrl);
      };
      image.onerror = () => {
        URL.revokeObjectURL(url);
        reject(new Error("Image load failed"));
      };
      image.src = url;
    });
  }
  async onClose() {
    var _a;
    (_a = this.previewContainer) == null ? void 0 : _a.empty();
    console.log("\u{1F34E} \u8F6C\u6362\u5668\u9762\u677F\u5DF2\u5173\u95ED");
  }
};
var AppleStyleSettingTab = class extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new Setting(containerEl).setDesc("\u66F4\u591A\u6392\u7248\u6837\u5F0F\u9009\u9879\uFF08\u4E3B\u9898\u3001\u5B57\u53F7\u3001\u4EE3\u7801\u5757\u7B49\uFF09\u8BF7\u5728\u63D2\u4EF6\u4FA7\u8FB9\u680F\u9762\u677F\u4E2D\u8FDB\u884C\u8BBE\u7F6E\u3002");
    new Setting(containerEl).setName("\u56FE\u7247\u6C34\u5370").setHeading();
    new Setting(containerEl).setName("\u542F\u7528\u56FE\u7247\u6C34\u5370").setDesc("\u5728\u6BCF\u5F20\u56FE\u7247\u4E0A\u65B9\u663E\u793A\u5934\u50CF").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableWatermark).onChange(async (value) => {
      this.plugin.settings.enableWatermark = value;
      await this.plugin.saveSettings();
    }));
    const uploadSetting = new Setting(containerEl).setName("\u4E0A\u4F20\u672C\u5730\u5934\u50CF").setDesc(this.plugin.settings.avatarBase64 ? "\u2705 \u5DF2\u4E0A\u4F20\u672C\u5730\u5934\u50CF\uFF08\u4F18\u5148\u4F7F\u7528\uFF09" : "\u9009\u62E9\u672C\u5730\u56FE\u7247\uFF0C\u8F6C\u6362\u4E3A Base64 \u5B58\u50A8\uFF0C\u65E0\u9700\u7F51\u7EDC\u8BF7\u6C42");
    uploadSetting.addButton((button) => button.setButtonText(this.plugin.settings.avatarBase64 ? "\u91CD\u65B0\u4E0A\u4F20" : "\u9009\u62E9\u56FE\u7247").onClick(() => {
      const input = document.createElement("input");
      input.type = "file";
      input.accept = "image/*";
      input.onchange = async (e) => {
        const file = e.target.files[0];
        if (!file) return;
        if (file.size > 100 * 1024) {
          new Notice("\u274C \u56FE\u7247\u592A\u5927\uFF0C\u8BF7\u9009\u62E9\u5C0F\u4E8E 100KB \u7684\u56FE\u7247");
          return;
        }
        const reader = new FileReader();
        reader.onload = async (event) => {
          this.plugin.settings.avatarBase64 = event.target.result;
          await this.plugin.saveSettings();
          new Notice("\u2705 \u5934\u50CF\u5DF2\u4E0A\u4F20");
          this.display();
        };
        reader.readAsDataURL(file);
      };
      input.click();
    }));
    if (this.plugin.settings.avatarBase64) {
      uploadSetting.addButton((button) => button.setButtonText("\u6E05\u9664").setWarning().onClick(async () => {
        this.plugin.settings.avatarBase64 = "";
        await this.plugin.saveSettings();
        new Notice("\u5DF2\u6E05\u9664\u672C\u5730\u5934\u50CF");
        this.display();
      }));
    }
    new Setting(containerEl).setName("\u5934\u50CF URL\uFF08\u5907\u7528\uFF09").setDesc("\u5982\u672A\u4E0A\u4F20\u672C\u5730\u5934\u50CF\uFF0C\u5C06\u4F7F\u7528\u6B64 URL").addText((text) => text.setPlaceholder("https://example.com/avatar.jpg").setValue(this.plugin.settings.avatarUrl).onChange(async (value) => {
      this.plugin.settings.avatarUrl = value;
      await this.plugin.saveSettings();
    }));
    new Setting(containerEl).setName("\u663E\u793A\u56FE\u7247\u8BF4\u660E\u6587\u5B57").setDesc("\u5173\u95ED\u6C34\u5370\u65F6\uFF0C\u5728\u56FE\u7247\u4E0B\u65B9\u663E\u793A\u8BF4\u660E\u6587\u5B57\uFF08\u56FE\u7247\u540D\u79F0\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.showImageCaption).onChange(async (value) => {
      this.plugin.settings.showImageCaption = value;
      await this.plugin.saveSettings();
    }));
    new Setting(containerEl).setName("\u5FAE\u4FE1\u516C\u4F17\u53F7\u8D26\u53F7").setDesc("\u5728\u516C\u4F17\u53F7\u540E\u53F0 [\u8BBE\u7F6E\u4E0E\u5F00\u53D1] -> [\u57FA\u672C\u914D\u7F6E] \u4E2D\u83B7\u53D6 AppID \u548C AppSecret\u3002\u5982\u679C IP \u7ECF\u5E38\u53D8\u5316\uFF0C\u5EFA\u8BAE\u914D\u7F6E\u4E0B\u65B9\u7684 API \u4EE3\u7406\u3002").setHeading();
    const accounts = this.plugin.settings.wechatAccounts || [];
    const defaultId = this.plugin.settings.defaultAccountId;
    if (accounts.length === 0) {
      containerEl.createEl("p", {
        text: "\u6682\u65E0\u8D26\u53F7\uFF0C\u8BF7\u70B9\u51FB\u4E0B\u65B9\u6309\u94AE\u6DFB\u52A0",
        cls: "setting-item-description",
        attr: { style: "color: var(--text-muted); font-style: italic;" }
      });
    } else {
      const listContainer = containerEl.createDiv({ cls: "wechat-account-list" });
      for (const account of accounts) {
        const isDefault = account.id === defaultId;
        const card = listContainer.createDiv({ cls: "wechat-account-card" });
        const info = card.createDiv({ cls: "wechat-account-info" });
        const nameRow = info.createDiv({ cls: "wechat-account-name-row" });
        nameRow.createSpan({ text: account.name, cls: "wechat-account-name" });
        if (isDefault) {
          nameRow.createSpan({ text: "\u9ED8\u8BA4", cls: "wechat-account-badge" });
        }
        info.createDiv({
          text: `AppID: ${account.appId.substring(0, 8)}...`,
          cls: "wechat-account-appid"
        });
        const actions = card.createDiv({ cls: "wechat-account-actions" });
        if (!isDefault) {
          const defaultBtn = actions.createEl("button", { text: "\u8BBE\u4E3A\u9ED8\u8BA4", cls: "wechat-btn-small" });
          defaultBtn.onclick = async () => {
            this.plugin.settings.defaultAccountId = account.id;
            await this.plugin.saveSettings();
            this.display();
          };
        }
        const editBtn = actions.createEl("button", { text: "\u7F16\u8F91", cls: "wechat-btn-small" });
        editBtn.onclick = () => this.showEditAccountModal(account);
        const testBtn = actions.createEl("button", { text: "\u6D4B\u8BD5", cls: "wechat-btn-small wechat-btn-test" });
        testBtn.onclick = async () => {
          testBtn.disabled = true;
          testBtn.textContent = "\u6D4B\u8BD5\u4E2D...";
          try {
            const api = new WechatAPI(account.appId, account.appSecret, this.plugin.settings.proxyUrl);
            await api.getAccessToken();
            new Notice(`\u2705 ${account.name} \u8FDE\u63A5\u6210\u529F\uFF01`);
          } catch (err) {
            new Notice(`\u274C ${account.name} \u8FDE\u63A5\u5931\u8D25: ${err.message}`);
          }
          testBtn.disabled = false;
          testBtn.textContent = "\u6D4B\u8BD5";
        };
        const deleteBtn = actions.createEl("button", { text: "\u5220\u9664", cls: "wechat-btn-small wechat-btn-danger" });
        deleteBtn.onclick = async () => {
          if (confirm(`\u786E\u5B9A\u8981\u5220\u9664\u8D26\u53F7 "${account.name}" \u5417\uFF1F`)) {
            this.plugin.settings.wechatAccounts = accounts.filter((a) => a.id !== account.id);
            if (account.id === defaultId && this.plugin.settings.wechatAccounts.length > 0) {
              this.plugin.settings.defaultAccountId = this.plugin.settings.wechatAccounts[0].id;
            } else if (this.plugin.settings.wechatAccounts.length === 0) {
              this.plugin.settings.defaultAccountId = "";
            }
            await this.plugin.saveSettings();
            this.display();
          }
        };
      }
    }
    const addBtnContainer = containerEl.createDiv({ cls: "wechat-add-account-container" });
    if (accounts.length < MAX_ACCOUNTS) {
      const addBtn = addBtnContainer.createEl("button", {
        text: "+ \u6DFB\u52A0\u8D26\u53F7",
        cls: "wechat-btn-add"
      });
      addBtn.onclick = () => this.showEditAccountModal(null);
    } else {
      addBtnContainer.createEl("p", {
        text: `\u5DF2\u8FBE\u5230\u6700\u5927\u8D26\u53F7\u6570\u91CF (${MAX_ACCOUNTS})`,
        cls: "setting-item-description",
        attr: { style: "color: var(--text-muted);" }
      });
    }
    new Setting(containerEl).setName("\u9AD8\u7EA7\u8BBE\u7F6E").setHeading();
    new Setting(containerEl).setName("API \u4EE3\u7406\u5730\u5740").setDesc(createFragment((frag) => {
      frag.appendText("\u5982\u679C\u4F60\u7684 IP \u7ECF\u5E38\u53D8\u5316\u6216\u4F7F\u7528\u4E86 VPN\uFF0C\u5FAE\u4FE1 API \u7684 IP \u767D\u540D\u5355\u4F1A\u9891\u7E41\u5931\u6548\u3002");
      frag.createEl("br");
      frag.appendText("\u89E3\u51B3\u65B9\u6848\uFF1A\u90E8\u7F72\u4E00\u4E2A Cloudflare Worker \u4F5C\u4E3A\u56FA\u5B9A IP \u4EE3\u7406\uFF0C\u8BA9\u6240\u6709 API \u8BF7\u6C42\u901A\u8FC7\u4EE3\u7406\u8F6C\u53D1\u3002");
      frag.createEl("br");
      frag.createEl("strong", { text: "\u6B65\u9AA4\uFF1A" });
      frag.appendText(" 1) \u6CE8\u518C Cloudflare -> 2) \u521B\u5EFA Worker -> 3) \u5C06 Worker URL \u586B\u5165\u6B64\u5904 -> 4) \u628A Worker \u7684 IP \u52A0\u5165\u5FAE\u4FE1\u767D\u540D\u5355");
      frag.createEl("br");
      frag.createEl("a", {
        text: "\u67E5\u770B\u90E8\u7F72\u6307\u5357",
        href: "https://xiaoweibox.top/chats/wechat-proxy"
      });
    })).addText((text) => text.setPlaceholder("https://your-proxy.workers.dev").setValue(this.plugin.settings.proxyUrl).onChange(async (value) => {
      this.plugin.settings.proxyUrl = value.trim();
      await this.plugin.saveSettings();
    }));
  }
  /**
   * 显示添加/编辑账号的模态框
   */
  showEditAccountModal(account) {
    const { Modal } = require("obsidian");
    const modal = new Modal(this.app);
    modal.titleEl.setText(account ? "\u7F16\u8F91\u8D26\u53F7" : "\u6DFB\u52A0\u8D26\u53F7");
    const form = modal.contentEl.createDiv();
    const nameGroup = form.createDiv({ cls: "wechat-form-group" });
    nameGroup.createEl("label", { text: "\u8D26\u53F7\u540D\u79F0" });
    const nameInput = nameGroup.createEl("input", { attr: { type: "text", placeholder: "\u4F8B\u5982\uFF1A\u6211\u7684\u516C\u4F17\u53F7" } });
    nameInput.value = (account == null ? void 0 : account.name) || "";
    const appIdGroup = form.createDiv({ cls: "wechat-form-group" });
    appIdGroup.createEl("label", { text: "AppID" });
    const appIdInput = appIdGroup.createEl("input", { attr: { type: "text", placeholder: "wx..." } });
    appIdInput.value = (account == null ? void 0 : account.appId) || "";
    const secretGroup = form.createDiv({ cls: "wechat-form-group" });
    secretGroup.createEl("label", { text: "AppSecret" });
    const secretInput = secretGroup.createEl("input", { attr: { type: "password", placeholder: "\u5F00\u53D1\u8005\u5BC6\u94A5" } });
    secretInput.value = (account == null ? void 0 : account.appSecret) || "";
    const authorGroup = form.createDiv({ cls: "wechat-form-group" });
    authorGroup.createEl("label", { text: "\u9ED8\u8BA4\u4F5C\u8005\uFF08\u53EF\u9009\uFF09" });
    const authorInput = authorGroup.createEl("input", { attr: { type: "text", placeholder: "\u7559\u7A7A\u5219\u4E0D\u663E\u793A\u4F5C\u8005" } });
    authorInput.value = (account == null ? void 0 : account.author) || "";
    const btnRow = form.createDiv({ cls: "wechat-modal-buttons" });
    const cancelBtn = btnRow.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.onclick = () => modal.close();
    const testBtn = btnRow.createEl("button", { text: "\u6D4B\u8BD5\u8FDE\u63A5", cls: "wechat-btn-test" });
    testBtn.onclick = async () => {
      if (!appIdInput.value || !secretInput.value) {
        new Notice("\u8BF7\u586B\u5199 AppID \u548C AppSecret");
        return;
      }
      testBtn.disabled = true;
      testBtn.textContent = "\u6D4B\u8BD5\u4E2D...";
      try {
        const api = new WechatAPI(appIdInput.value.trim(), secretInput.value.trim(), this.plugin.settings.proxyUrl);
        await api.getAccessToken();
        new Notice("\u2705 \u8FDE\u63A5\u6210\u529F\uFF01");
      } catch (err) {
        new Notice(`\u274C \u8FDE\u63A5\u5931\u8D25: ${err.message}`);
      }
      testBtn.disabled = false;
      testBtn.textContent = "\u6D4B\u8BD5\u8FDE\u63A5";
    };
    const saveBtn = btnRow.createEl("button", { text: "\u4FDD\u5B58", cls: "mod-cta" });
    saveBtn.onclick = async () => {
      const name = nameInput.value.trim() || "\u672A\u547D\u540D\u8D26\u53F7";
      const appId = appIdInput.value.trim();
      const appSecret = secretInput.value.trim();
      if (!appId || !appSecret) {
        new Notice("\u8BF7\u586B\u5199 AppID \u548C AppSecret");
        return;
      }
      if (account) {
        account.name = name;
        account.appId = appId;
        account.appSecret = appSecret;
        account.author = authorInput.value.trim();
      } else {
        const newAccount = {
          id: generateId(),
          name,
          appId,
          appSecret,
          author: authorInput.value.trim()
        };
        this.plugin.settings.wechatAccounts.push(newAccount);
        if (this.plugin.settings.wechatAccounts.length === 1) {
          this.plugin.settings.defaultAccountId = newAccount.id;
        }
      }
      await this.plugin.saveSettings();
      modal.close();
      this.display();
      new Notice(account ? "\u2705 \u8D26\u53F7\u5DF2\u66F4\u65B0" : "\u2705 \u8D26\u53F7\u5DF2\u6DFB\u52A0");
    };
    modal.open();
  }
};
var AppleStylePlugin = class extends Plugin {
  async onload() {
    console.log("\u{1F4DD} \u6B63\u5728\u52A0\u8F7D\u5FAE\u4FE1\u516C\u4F17\u53F7\u8F6C\u6362\u5668...");
    await this.loadSettings();
    this.registerView(
      APPLE_STYLE_VIEW,
      (leaf) => new AppleStyleView(leaf, this)
    );
    this.addRibbonIcon("wand", "\u{1F4DD} \u5FAE\u4FE1\u516C\u4F17\u53F7\u8F6C\u6362\u5668", async () => {
      await this.openConverter();
    });
    this.addCommand({
      id: "open-apple-converter",
      name: "\u6253\u5F00\u5FAE\u4FE1\u516C\u4F17\u53F7\u8F6C\u6362\u5668",
      callback: async () => {
        await this.openConverter();
      }
    });
    this.addSettingTab(new AppleStyleSettingTab(this.app, this));
    console.log("\u2705 \u5FAE\u4FE1\u516C\u4F17\u53F7\u8F6C\u6362\u5668\u52A0\u8F7D\u5B8C\u6210");
  }
  async openConverter() {
    let leaf = this.app.workspace.getLeavesOfType(APPLE_STYLE_VIEW)[0];
    if (!leaf) {
      const rightLeaf = this.app.workspace.getRightLeaf(false);
      await rightLeaf.setViewState({
        type: APPLE_STYLE_VIEW,
        active: true
      });
      leaf = rightLeaf;
    }
    this.app.workspace.revealLeaf(leaf);
  }
  getConverterView() {
    const leaves = this.app.workspace.getLeavesOfType(APPLE_STYLE_VIEW);
    if (leaves.length > 0) {
      return leaves[0].view;
    }
    return null;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (this.settings.wechatAppId && this.settings.wechatAccounts.length === 0) {
      const migratedAccount = {
        id: generateId(),
        name: "\u6211\u7684\u516C\u4F17\u53F7",
        appId: this.settings.wechatAppId,
        appSecret: this.settings.wechatAppSecret
      };
      this.settings.wechatAccounts.push(migratedAccount);
      this.settings.defaultAccountId = migratedAccount.id;
      this.settings.wechatAppId = "";
      this.settings.wechatAppSecret = "";
      await this.saveSettings();
      console.log("\u2705 \u5DF2\u5C06\u65E7\u8D26\u53F7\u914D\u7F6E\u8FC1\u79FB\u5230\u65B0\u683C\u5F0F");
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    console.log("\u{1F4DD} \u5FAE\u4FE1\u516C\u4F17\u53F7\u8F6C\u6362\u5668\u5DF2\u5378\u8F7D");
  }
};
module.exports = AppleStylePlugin;
